import type { Employee, Equipment } from '../types';

export const mockEmployees: Employee[] = [
  { employeeId: 'EMP-0001', name: 'Andrea Villanueva', status: 'Active', position: 'Administrative Officer V' },
  { employeeId: 'EMP-0002', name: 'Miguel Santos', status: 'Active', position: 'Science Research Specialist II' },
  { employeeId: 'EMP-0003', name: 'Carmela Reyes', status: 'Active', position: 'Property Custodian' },
  { employeeId: 'EMP-0004', name: 'Jonas Mercado', status: 'Transferred', position: 'IT Officer I' },
  { employeeId: 'EMP-0005', name: 'Leah Mendoza', status: 'Active', position: 'Laboratory Technician' },
];

export const mockEquipments: Equipment[] = [
  {
    id: 'eq-001',
    category: 'PPE ACCOUNTABILITY',
    article: 'Laptop Computer',
    propertyNo: 'ICT-2026-0001',
    itemDescription: '13-inch ultrabook, 16GB RAM, 512GB SSD',
    amount: 68500,
    accountabilityNo: 'PAR-2026-001',
    accountabilityType: 'PAR',
    issuedTo: 'Andrea Villanueva',
    dateIssued: '2026-01-14',
    status: 'Assigned',
    location: 'Admin Office',
    remarks: 'Primary workstation',
    updatedAt: '2026-05-18T08:10:00.000Z',
  },
  {
    id: 'eq-002',
    category: 'TECHNICAL AND SCIENTIFIC EQUIPMENTS',
    article: 'Digital Microscope',
    propertyNo: 'LAB-2025-0042',
    itemDescription: 'High-resolution digital microscope with imaging module',
    amount: 142000,
    accountabilityNo: 'PAR-2025-087',
    accountabilityType: 'PAR',
    issuedTo: 'Leah Mendoza',
    dateIssued: '2025-09-04',
    status: 'Assigned',
    location: 'Laboratory 2',
    remarks: 'Calibrated Q1 2026',
    updatedAt: '2026-05-15T03:42:00.000Z',
  },
  {
    id: 'eq-003',
    category: 'SEMI-EXPENDABLE PROPERTY (SE)',
    article: 'Office Chair',
    propertyNo: 'SE-2026-0099',
    itemDescription: 'Ergonomic mesh task chair',
    amount: 8700,
    accountabilityNo: 'ICS-2026-023',
    accountabilityType: 'ICS',
    issuedTo: 'Miguel Santos',
    dateIssued: '2026-02-08',
    status: 'Assigned',
    location: 'Research Office',
    remarks: 'New issue',
    updatedAt: '2026-05-12T01:21:00.000Z',
  },
  {
    id: 'eq-004',
    category: 'OFFICE EQUIPMENTS - EXPANDABLES',
    article: 'Laser Printer',
    propertyNo: 'OE-2024-0017',
    itemDescription: 'Monochrome network laser printer',
    amount: 22800,
    accountabilityNo: 'PAR-2024-044',
    accountabilityType: 'PAR',
    issuedTo: '',
    dateIssued: '',
    status: 'Available',
    location: 'Supply Room',
    remarks: 'Ready for assignment',
    updatedAt: '2026-05-10T02:05:00.000Z',
  },
  {
    id: 'eq-005',
    category: 'SUPPLIES AND SEMI-EXPENDABLES/OFFICE EQUIPMENT',
    article: 'Document Scanner',
    propertyNo: 'SUP-2025-0210',
    itemDescription: 'Duplex sheet-fed scanner',
    amount: 31500,
    accountabilityNo: 'PAR-2025-111',
    accountabilityType: 'PAR',
    issuedTo: 'Carmela Reyes',
    dateIssued: '2025-11-18',
    status: 'For Repair',
    location: 'Records Unit',
    remarks: 'Feeder needs service',
    updatedAt: '2026-05-09T06:22:00.000Z',
  },
];
